### ISSUE TITLE
Look into git authors plugin doing wonky duplication

### ISSUE THREAD

**Issue by Berserkir-Wolf** [Haututu-Hacklab/Guides#22]
Plugin appears to be double-displaying when deployed with github actions. Need to troubleshoot in venv to try reproduce, see if it's a material or mkdocs source issue.

**Comment by ZaneA** [comment]
FWIW the deployed version and my local appear identical (after doing `pip install mkdocs-git-authors-plugin` locally).

![Screenshot from 2024-08-21 20-29-40](https://github.com/user-attachments/assets/ae355768-57f1-48bb-9833-8279d6a30029)

Edit: I should add that this was on `main`

**Comment by Berserkir-Wolf** [comment]
Yet when I do it from development on my machine (after merging main into dev) it shows a single line, not a duplicate.
I've disabled the overrides for the time being, as supposedly mkdocs-material no longer needs an override. It appears to look decent, so will see how it goes over the next few deployments.

**Comment by Berserkir-Wolf** [comment]
Couple changes done, still looking good, so should be done.
